services:
  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ruby-bundle-cache:/bundle
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data
  db:
    env_file: .env
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
volumes:
  ruby-bundle-cache:
    external: true